# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from py_client.proto import calc_pb2 as proto_dot_calc__pb2


class CalcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/proto.CalcService/Add',
                request_serializer=proto_dot_calc__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_calc__pb2.Response.FromString,
                )
        self.Sub = channel.unary_unary(
                '/proto.CalcService/Sub',
                request_serializer=proto_dot_calc__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_calc__pb2.Response.FromString,
                )
        self.Mul = channel.unary_unary(
                '/proto.CalcService/Mul',
                request_serializer=proto_dot_calc__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_calc__pb2.Response.FromString,
                )
        self.Div = channel.unary_unary(
                '/proto.CalcService/Div',
                request_serializer=proto_dot_calc__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_calc__pb2.Response.FromString,
                )


class CalcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mul(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Div(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=proto_dot_calc__pb2.Request.FromString,
                    response_serializer=proto_dot_calc__pb2.Response.SerializeToString,
            ),
            'Sub': grpc.unary_unary_rpc_method_handler(
                    servicer.Sub,
                    request_deserializer=proto_dot_calc__pb2.Request.FromString,
                    response_serializer=proto_dot_calc__pb2.Response.SerializeToString,
            ),
            'Mul': grpc.unary_unary_rpc_method_handler(
                    servicer.Mul,
                    request_deserializer=proto_dot_calc__pb2.Request.FromString,
                    response_serializer=proto_dot_calc__pb2.Response.SerializeToString,
            ),
            'Div': grpc.unary_unary_rpc_method_handler(
                    servicer.Div,
                    request_deserializer=proto_dot_calc__pb2.Request.FromString,
                    response_serializer=proto_dot_calc__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.CalcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.CalcService/Add',
            proto_dot_calc__pb2.Request.SerializeToString,
            proto_dot_calc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.CalcService/Sub',
            proto_dot_calc__pb2.Request.SerializeToString,
            proto_dot_calc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Mul(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.CalcService/Mul',
            proto_dot_calc__pb2.Request.SerializeToString,
            proto_dot_calc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Div(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.CalcService/Div',
            proto_dot_calc__pb2.Request.SerializeToString,
            proto_dot_calc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
